---
- name: Get Lighthouse
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip"
    dest: "./lighthouse_arch.zip"
    mode: 0644

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    pkg:
    - unzip

- name: Create directiry
  become: true
  ansible.builtin.file:
    path: ./lh
    state: directory
    mode: 0777

- name: Unzip Lighthouse
  ansible.builtin.unarchive:
    src: ./lighthouse_arch.zip
    dest: ./lh/
    remote_src: true

- name: Copy config for Lighthouse
  become: true
  ansible.builtin.template:
    mode: 0644
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: nginx restart
